// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

func buildTargets() -> [Target] {
    let realmVersion = "10.44.0"
    let xcodeVersion = "15.1"
    let realmBaseURL = "https://github.com/realm/realm-swift/releases/download/v\(realmVersion)"
    /// Generated by going to the downloads folder and run `swift package compute-checksum Realm.spm.zip`
    let realmChecksum = "b26c979ce122acaabb6a6eef9567de43344377afa825c597ae6e14caf508c225"
    /// Generated by running: `swift package compute-checksum RealmSwift@15.1.spm.zip`
    let realmSwiftChecksum = "acc10a6a5e0dd285be81b487dc0ff8379f8abaf43bde769f9452843ddb81a383"
    return [
        .binaryTarget(
            name: "RealmBinary",
            url: "\(realmBaseURL)/Realm.spm.zip",
            checksum: realmChecksum
        ),
        .binaryTarget(
            name: "RealmSwiftBinary",
            url: "\(realmBaseURL)/RealmSwift@\(xcodeVersion).spm.zip",
            checksum: realmSwiftChecksum
        )
    ]
}

let package = Package(
    name: "RealmBinaryDependency",
    platforms: [
      .macOS(.v10_13), .iOS(.v12), .tvOS(.v12), .watchOS(.v4)
    ],
    products: [
        .library(
             name: "RealmBinary",
             targets: ["RealmBinary"]
           ),
           .library(
             name: "RealmSwiftBinary",
             targets: ["RealmBinary", "RealmSwiftBinary"]
           )
    ],
    targets: buildTargets()
)
